name: Build_release

on:
  push:
    branches: [ "master" ]

jobs:
  
  
  build:
  
    runs-on: windows-latest   
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build publish
      run: dotnet publish --no-restore -c Release

    - name: Create zip       
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'L2HS.zip'        
        directory: ${{ github.workspace }}\MainMenu\bin\Release\net7.0-windows\publish 
        exclusions: '*.pdb LevelEditor.exe WPFUserInterface.exe'
        
    - name: Create release  
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.workspace }}\MainMenu\bin\Release\net7.0-windows\publish\L2HS.zip
        generateReleaseNotes: true
        name: v${{ github.run_number }}
        tag: Latest
        omitNameDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}
